'use strict';

const RTMUser = require('./user.js');
const _get = require('./utils/get.js');
const _auth = require('./utils/auth.js');


/**
 * ### RTM API Client
 *
 * This Class is used to represent an RTM API Client.  The Client contains
 * the API Key, API Secret and access permissions used to access the
 * RTM API endpoints.
 *
 * It also includes API wrapper functions for making a general RTM API request
 * as well as the auth-related functions.
 *
 * #### Usage
 *
 * The `RTMClient` Class is what is exported when the entire `rtm-api` module
 * is loaded via `require`.
 *
 * ```
 * const RTM = require('rtm-api');
 * let client = new RTM(API_KEY, API_SECRET, RTM.PERM_DELETE);
 * ```
 *
 * #### Auth Example
 *
 * This example gets an Auth URL to be opened by the RTM User
 *
 * ```
 * client.auth.getAuthUrl(function(err, authUrl, frob) {
 *    // Have user authenticate and authorize the program with the authUrl
 *    // Once authorized by the user, use the frob to get an authToken
 * )};
 * ```
 *
 * #### RTM API Example
 *
 * This example makes an RTM API request using the method `rtm.method` and the
 * parameter foo=bar.
 *
 * ```
 * client.get('rtm.method', {foo: "bar"}, function(resp) {
 *    if ( !resp.isOk ) {
 *      // handle error
 *    }
 *    // use the response
 * });
 * ```
 *
 * See {@link RTMUser#get|RTMUser.get} for making User-authenticated API requests.
 *
 * @class
 */
class RTMClient {

  /**
   * Create a new RTM Client with the specified API access information
   * @param {string} key RTM API Client Key
   * @param {string} secret RTM API Client Secret
   * @param {string} [perms=RTMClient.PERM_READ] RTM API Client Access Permissions. This
   * should be one of {@link RTMClient.PERM_READ}, {@link RTMClient.PERM_WRITE} or
   * {@link RTMClient.PERM_DELETE}.
   * @constructor
   */
  constructor(key, secret, perms=RTMClient.PERM_READ) {
    this._apiKey = key;
    this._apiSecret = secret;
    this._perms = perms;
  }


  /**
   * RTM API Client Key
   * @returns {string}
   */
  get key() {
    return this._apiKey;
  }

  /**
   * RTM API Client Secret
   * @returns {string}
   */
  get secret() {
    return this._apiSecret;
  }

  /**
   * RTM API Client Access Permissions
   * @returns {string}
   */
  get perms() {
    return this._perms;
  }


  /**
   * Create a new `RTMUser` manually.
   *
   * This will also set the User's RTM API Client to this `RTMClient`.
   * @param {number} id The RTM User's ID
   * @param {string} username The RTM User's username
   * @param {string} fullname The RTM User's full name
   * @param {string} authToken The RTM User's Auth Token
   * @returns {RTMUser}
   */
  user(id, username, fullname, authToken) {
    let user = new RTMUser(id, username, fullname, authToken);
    user.client = this;
    return user;
  }



  // ===== API HELPER FUNCTIONS ===== //


  /**
   * Make the specified RTM API call.
   *
   * The `method` should be the name of the RTM API method.  Any necessary
   * parameters should be provided with `params` as an object with the properties
   * of the object as the parameters' key/value pairs.
   *
   * RTM API methods that require an AuthToken should set the `params` `auth_token`
   * property or provide a valid `RTMUser` with an AuthToken.
   * @param {string} method RTM API Method
   * @param {object} [params={}] RTM Method Parameters (as an object with key/value pairs)
   * @param {RTMUser} [user=undefined] The RTM User making the request
   * @param {function} callback Callback function(resp)
   * @param {RTMError|RTMSuccess} callback.resp The parsed RTM API Response
   */
  get(method, params, user, callback) {
    _get(method, params, user, this, callback);
  }


  /**
   * Auth-related functions:
   * - {@link RTMClient~auth/getAuthUrl|getAuthUrl}
   * - {@link RTMClient~auth/getAuthToken|getAuthToken}
   * - {@link RTMClient~auth/verifyAuthToken|verifyAuthToken}
   * @returns {{}}
   */
  get auth() {
    let rtn = {};
    let _client = this;

    /**
     * Get an Auth URL.
     *
     * This function will generate an Auth URL that will be given to the RTM User
     * to authorize the RTM Client to access their account.  It will also request
     * a frob that will be used to gain an auth token in `getAuthToken()`.
     * @param {function} callback Callback function(err, authUrl, frob)
     * @param {RTMError} callback.err RTM Error Response, if encountered
     * @param {string} callback.authUrl Auth URL to be given to User
     * @param {string} callback.frob Auth Frob to be used in `getAuthToken()`
     * @function RTMClient~auth/getAuthUrl
     */
    rtn.getAuthUrl = function(callback) {
      _auth.getAuthUrl(_client, callback);
    };

    /**
     * Get an Auth Token.
     *
     * This function takes the frob that was generated by `getAuthUrl()` and
     * requests an Auth Token.  The callback function will return an `RTMUser`
     * which will include the RTM User's information and an Auth Token to be
     * used in future API calls.
     * @param {string} frob Auth Frob from `getAuthUrl()`
     * @param {function} callback Callback function(err, user)
     * @param {RTMError} callback.err RTM Error Response, if encountered
     * @param {RTMUser} callback.user RTM User, with user information and auth token
     * @function RTMClient~auth/getAuthToken
     */
    rtn.getAuthToken = function(frob, callback) {
      _auth.getAuthToken(frob, _client, callback);
    };

    /**
     * Verify Auth Token.
     *
     * This function will check if the User's Auth Token is still valid and
     * can be used to make authenticated RTM API requests.
     * @param {string|RTMUser} token Auth Token or RTMUser containing an auth token
     * @param {function} callback Callback function(verified)
     * @param {boolean} callback.verified True if the User's auth token was successfully verified
     * @function RTMClient~auth/verifyAuthToken
     */
    rtn.verifyAuthToken = function(token, callback) {
      _auth.verifyAuthToken(token, _client, callback);
    };

    return rtn;
  }

}


// ==== RTM USER IMPORT / EXPORT ==== //

/**
 * Convert a User's required information to a JSON string
 * @param {RTMUser} user The RTMUser to convert
 */
RTMClient.userToString = function(user) {
  return RTMUser.toString(user);
};

/**
 * Create a RTM User from a JSON string
 * @param {string} string JSON string of User's required information
 * @returns {RTMUser}
 */
RTMClient.userFromString = function(string) {
  return RTMUser.fromString(string);
};



// ==== RTM API PERMISSION LEVELS ==== //

/**
 * RTM API Access: `read` -
 * gives the ability to read task, contact, group and list details and contents.
 * @type {string}
 * @default
 */
RTMClient.PERM_READ = 'read';

/**
 * RTM API Access: `write` -
 * gives the ability to add and modify task, contact, group and list details and
 * contents (also allows you to `read`).
 * @type {string}
 * @default
 */
RTMClient.PERM_WRITE = 'write';

/**
 * RTM API Access: `delete` -
 * gives the ability to delete tasks, contacts, groups and lists (also allows
 * you to `read` and `write`).
 * @type {string}
 * @default
 */
RTMClient.PERM_DELETE = 'delete';



module.exports = RTMClient;
